[phases.setup]
nixPkgs = [
    "python311",
    "libGL", 
    "libGLU",
    "mesa",
    "xorg.libX11",
    "xorg.libXext",
    "xorg.libXrender",
    "fontconfig",
    "freetype"
]

[variables]
LD_LIBRARY_PATH = "/nix/store/*/lib:/usr/lib"
PYTHONUNBUFFERED = "1"

[phases.build]
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[start]
cmd = "gunicorn server:app --bind 0.0.0.0:$PORT --workers 1 --timeout 600 --threads 2 --max-requests 100" 