[phases.setup]
nixPkgs = [
  "python311",
  "libGL",
  "libGLU", 
  "xorg.libX11",
  "xorg.libXext",
  "xorg.libXrender",
  "xorg.libSM",
  "xorg.libICE",
  "glib",
  "fontconfig",
  "freetype"
]

[phases.build]
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[start]
cmd = "gunicorn server:app --bind 0.0.0.0:$PORT --workers 1 --timeout 600 --threads 2 --max-requests 100" 