[phases.setup]
nixPkgs = [
    "python311",
    "python311Packages.pip",
    "mesa",
    "libGL",
    "libGLU",
    "xorg.libX11",
    "xorg.libXext",
    "xorg.libXrender",
    "fontconfig",
    "freetype",
    "glib"
]

[variables]
PYTHONUNBUFFERED = "1"
LD_LIBRARY_PATH = "/nix/store/*/lib"

[start]
cmd = "gunicorn server:app --bind 0.0.0.0:$PORT --workers 1 --timeout 600" 